#!/bin/bash
#
# reload the stmpe_ts module to fix touchscreen issue 2/20/2020 
#
sudo rmmod stmpe_ts
sudo modprobe stmpe_ts 
echo "On line below, /dev/input/touchscreen should point to eventn"
sleep 1
ls -l /dev/input/touchscreen